version: '2'
networks:
  local_net: 
    external:
      name: local 

volumes:
  dbdata:
    driver: local
services:
  myapp:
    image: 'docker.io/bitnami/codeigniter:3-debian-10'
    ports:
      - '8301:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
    networks:
      - local_net
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - local_net
